### PR TITLE
Cops 165.2

### PR DESCRIPTION
**Pull request by thilinapiy**
Revert 4XX from error page.

### CODE REVIEW

**Comment by AndyMoore111** [comment]
LGTM

**Comment by devlinmr** [comment]
LGTM

**Comment by thilinapiy** [comment]
I have update this PR.

**Comment by bsomogyi** [comment]
Do not merge until tests have been created and a release approach is identified in the PR.  

@thilinapiy - we are going away from monolithic a/b deploys of our system, so from this point forward we need engineers to identify the release approach for their change until we can re-invent our overall release strategy for all components of our system.

**Comment by thilinapiy** [comment]
https://github.com/pearsontechnology/docs/pull/14

**Pull request merged**
